name: 2 Jobs communication
on: [push]
jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: set variable
              id: job_1_output
              run: echo "JOB_1_OUTPUT=Chintu World!" >> $GITHUB_ENV
    
    job_2:
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - run: echo "${{ env.JOB_1_OUTPUT }}"
