name: 2 Jobs communication
on: [push]
jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: set variable
              env:
                  JOB_1_OUTPUT: Chintu World!
    
    job_2:
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - run: echo "${{ env.JOB_1_OUTPUT }}"
